language: go

addons:
  firefox: latest

install:
  - go get -u github.com/jteeuwen/go-bindata/...
  - go get -u -d github.com/Jumpscale/go-raml
  - npm install

go:
  - 1.7
  - master

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - cd $GOPATH/src/github.com/Jumpscale/go-raml && ./build.sh && cd -
  - go generate
  - go test -v ./...
  - npm test
